name: loggman
version: 0.1.0.0
github: 'kk0000-kk/loggman'
license: MIT
author: 'kk0000-kk'
maintainer: 'kazuyoshi.kobayashi.1@gmail.com'
copyright: '2025 kk0000-kk'

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/kk0000-kk/loggman#readme>

dependencies:
  - base >= 4.7 && < 5
  - text
  - filepath
  - time
  - process
  - directory
  - haskeline
  - yaml
  - unordered-containers
  - req
  - aeson
  - hashable
  - bytestring

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  loggman:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - loggman

tests:
  loggman-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - loggman
